<?php
/** @var \Amasty\AndyModule\Block\Index $block */
?>

<div>
    <form class=<?=$block->hasData("css_class_1") ? $block->getData("css_class_1") : ""?> name="form_a" method="post" action="">
        Код товара:<br>
        <input type="text" class=<?=$block->hasData("css_class_2") ? $block->getData("css_class_2") : ""?> id="skuid" name="sku" value=""><br>
        <?=$block->showInputQty()?>
        <?=$block->getChildHtml("andyModule.additional")?>
        <input type="submit" class=<?=$block->hasData("css_class_4") ? $block->getData("css_class_4") : ""?> id="buttonid" name="button" value="Отправить">
    </form>
</div>
