<div data-bind="scope:'anyTimer'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
</div>

<script type="text/x-magento-init">
   {
       "*": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "anyTimer": {
                       "component": "Amasty_AndyModule/js/koTimer",
                       "template" : "Amasty_AndyModule/koTimer"
                   }
               }
           }
       }
   }
</script>
